name: Terraform RG + StorageAccount per env

on:
  push:
    branches:
      - dev
      - prod
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest

    # GitHub Environment 
    environment: ${{ github.ref_name }}   # 'dev' eller 'prod'

    env:
      WORKDIR: "module06/terraform-projects/rg"
      BACKEND_HCL: "module06/terraform-projects/shared/backend.hcl"

      # ENVIRONMENT = branch navn (dev/prod)
      ENVIRONMENT: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"

      # Łoad variables fra Key Vault → TF_VAR_*
      - name: Load vars from Key Vault → TF_VAR_*
        env:
          KV: ${{ secrets.KEYVAULT_NAME }}   
        run: |
          set -euo pipefail

          RGNAME=$(az keyvault secret show --vault-name "$KV" --name demo-rgname   --query value -o tsv)
          LOCATION=$(az keyvault secret show --vault-name "$KV" --name demo-location --query value -o tsv)

          {
            echo "TF_VAR_rgname=$RGNAME"
            echo "TF_VAR_location=$LOCATION"
            echo "TF_VAR_environment=${ENVIRONMENT}"
          } >> "$GITHUB_ENV"

      - name: Terraform Init (AzureRM backend)
        working-directory: ${{ env.WORKDIR }}
        run: |
          terraform init -input=false \
            -backend-config="${{ github.workspace }}/${{ env.BACKEND_HCL }}" \
            -backend-config="key=LearnIaC/env/${{ env.ENVIRONMENT }}/rg.tfstate"

      - name: Terraform Validate
        working-directory: ${{ env.WORKDIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.WORKDIR }}
        run: terraform plan -input=false

      - name: Terraform Apply (only on prod via PR, on dev normal)
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
        working-directory: ${{ env.WORKDIR }}
        run: terraform apply -auto-approve -input=false
